# Generated by Django 5.1.2 on 2024-10-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_board_post_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=50000, verbose_name='Isi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Maksimal 50 karakter', max_length=200, verbose_name='Judul'),
        ),
    ]
