# Generated by Django 5.1.2 on 2024-10-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=50000, verbose_name='Komentar')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
