# Generated by Django 5.1.2 on 2024-10-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_comment_options_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.ImageField(null=True, upload_to='attachment'),
        ),
    ]
