# Generated by Django 5.1.2 on 2024-10-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_post_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ImageField(blank=True, help_text='maksimal gambar berukuran 500kb', null=True, upload_to='attachment'),
        ),
    ]
